# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('__x64dbg', [dirname(__file__)])
        except ImportError:
            import __x64dbg
            return __x64dbg
        if fp is not None:
            try:
                _mod = imp.load_module('__x64dbg', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    __x64dbg = swig_import_helper()
    del swig_import_helper
else:
    import __x64dbg
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def DbgMemRead(va, dest, size):
    return __x64dbg.DbgMemRead(va, dest, size)
DbgMemRead = __x64dbg.DbgMemRead

def DbgMemWrite(va, src, size):
    return __x64dbg.DbgMemWrite(va, src, size)
DbgMemWrite = __x64dbg.DbgMemWrite

def DbgMemGetPageSize(base):
    return __x64dbg.DbgMemGetPageSize(base)
DbgMemGetPageSize = __x64dbg.DbgMemGetPageSize

def DbgMemFindBaseAddr(addr, size):
    return __x64dbg.DbgMemFindBaseAddr(addr, size)
DbgMemFindBaseAddr = __x64dbg.DbgMemFindBaseAddr

def DbgCmdExec(cmd):
    return __x64dbg.DbgCmdExec(cmd)
DbgCmdExec = __x64dbg.DbgCmdExec

def DbgCmdExecDirect(cmd):
    return __x64dbg.DbgCmdExecDirect(cmd)
DbgCmdExecDirect = __x64dbg.DbgCmdExecDirect

def DbgIsValidExpression(expression):
    return __x64dbg.DbgIsValidExpression(expression)
DbgIsValidExpression = __x64dbg.DbgIsValidExpression

def DbgIsDebugging():
    return __x64dbg.DbgIsDebugging()
DbgIsDebugging = __x64dbg.DbgIsDebugging

def DbgIsJumpGoingToExecute(addr):
    return __x64dbg.DbgIsJumpGoingToExecute(addr)
DbgIsJumpGoingToExecute = __x64dbg.DbgIsJumpGoingToExecute

def DbgSetLabelAt(addr, text):
    return __x64dbg.DbgSetLabelAt(addr, text)
DbgSetLabelAt = __x64dbg.DbgSetLabelAt

def DbgGetCommentAt(addr, text):
    return __x64dbg.DbgGetCommentAt(addr, text)
DbgGetCommentAt = __x64dbg.DbgGetCommentAt

def DbgSetCommentAt(addr, text):
    return __x64dbg.DbgSetCommentAt(addr, text)
DbgSetCommentAt = __x64dbg.DbgSetCommentAt

def DbgGetBookmarkAt(addr):
    return __x64dbg.DbgGetBookmarkAt(addr)
DbgGetBookmarkAt = __x64dbg.DbgGetBookmarkAt

def DbgSetBookmarkAt(addr, isbookmark):
    return __x64dbg.DbgSetBookmarkAt(addr, isbookmark)
DbgSetBookmarkAt = __x64dbg.DbgSetBookmarkAt

def DbgGetModuleAt(addr, text):
    return __x64dbg.DbgGetModuleAt(addr, text)
DbgGetModuleAt = __x64dbg.DbgGetModuleAt

def DbgValFromString(string):
    return __x64dbg.DbgValFromString(string)
DbgValFromString = __x64dbg.DbgValFromString

def DbgValToString(string, value):
    return __x64dbg.DbgValToString(string, value)
DbgValToString = __x64dbg.DbgValToString

def DbgMemIsValidReadPtr(addr):
    return __x64dbg.DbgMemIsValidReadPtr(addr)
DbgMemIsValidReadPtr = __x64dbg.DbgMemIsValidReadPtr

def DbgGetBranchDestination(addr):
    return __x64dbg.DbgGetBranchDestination(addr)
DbgGetBranchDestination = __x64dbg.DbgGetBranchDestination

def DbgScriptLoad(filename):
    return __x64dbg.DbgScriptLoad(filename)
DbgScriptLoad = __x64dbg.DbgScriptLoad

def DbgScriptUnload():
    return __x64dbg.DbgScriptUnload()
DbgScriptUnload = __x64dbg.DbgScriptUnload

def DbgScriptRun(destline):
    return __x64dbg.DbgScriptRun(destline)
DbgScriptRun = __x64dbg.DbgScriptRun

def DbgScriptStep():
    return __x64dbg.DbgScriptStep()
DbgScriptStep = __x64dbg.DbgScriptStep

def DbgScriptBpToggle(line):
    return __x64dbg.DbgScriptBpToggle(line)
DbgScriptBpToggle = __x64dbg.DbgScriptBpToggle

def DbgScriptBpGet(line):
    return __x64dbg.DbgScriptBpGet(line)
DbgScriptBpGet = __x64dbg.DbgScriptBpGet

def DbgScriptCmdExec(command):
    return __x64dbg.DbgScriptCmdExec(command)
DbgScriptCmdExec = __x64dbg.DbgScriptCmdExec

def DbgScriptAbort():
    return __x64dbg.DbgScriptAbort()
DbgScriptAbort = __x64dbg.DbgScriptAbort

def DbgScriptSetIp(line):
    return __x64dbg.DbgScriptSetIp(line)
DbgScriptSetIp = __x64dbg.DbgScriptSetIp

def DbgAssembleAt(addr, instruction):
    return __x64dbg.DbgAssembleAt(addr, instruction)
DbgAssembleAt = __x64dbg.DbgAssembleAt

def DbgModBaseFromName(name):
    return __x64dbg.DbgModBaseFromName(name)
DbgModBaseFromName = __x64dbg.DbgModBaseFromName

def DbgSettingsUpdated():
    return __x64dbg.DbgSettingsUpdated()
DbgSettingsUpdated = __x64dbg.DbgSettingsUpdated

def DbgMenuEntryClicked(hEntry):
    return __x64dbg.DbgMenuEntryClicked(hEntry)
DbgMenuEntryClicked = __x64dbg.DbgMenuEntryClicked

def DbgFunctionGet(addr, start, end):
    return __x64dbg.DbgFunctionGet(addr, start, end)
DbgFunctionGet = __x64dbg.DbgFunctionGet

def DbgFunctionOverlaps(start, end):
    return __x64dbg.DbgFunctionOverlaps(start, end)
DbgFunctionOverlaps = __x64dbg.DbgFunctionOverlaps

def DbgFunctionAdd(start, end):
    return __x64dbg.DbgFunctionAdd(start, end)
DbgFunctionAdd = __x64dbg.DbgFunctionAdd

def DbgFunctionDel(addr):
    return __x64dbg.DbgFunctionDel(addr)
DbgFunctionDel = __x64dbg.DbgFunctionDel

def DbgLoopGet(depth, addr, start, end):
    return __x64dbg.DbgLoopGet(depth, addr, start, end)
DbgLoopGet = __x64dbg.DbgLoopGet

def DbgLoopOverlaps(depth, start, end):
    return __x64dbg.DbgLoopOverlaps(depth, start, end)
DbgLoopOverlaps = __x64dbg.DbgLoopOverlaps

def DbgLoopAdd(start, end):
    return __x64dbg.DbgLoopAdd(start, end)
DbgLoopAdd = __x64dbg.DbgLoopAdd

def DbgLoopDel(depth, addr):
    return __x64dbg.DbgLoopDel(depth, addr)
DbgLoopDel = __x64dbg.DbgLoopDel

def DbgIsRunLocked():
    return __x64dbg.DbgIsRunLocked()
DbgIsRunLocked = __x64dbg.DbgIsRunLocked

def DbgIsBpDisabled(addr):
    return __x64dbg.DbgIsBpDisabled(addr)
DbgIsBpDisabled = __x64dbg.DbgIsBpDisabled

def DbgSetAutoCommentAt(addr, text):
    return __x64dbg.DbgSetAutoCommentAt(addr, text)
DbgSetAutoCommentAt = __x64dbg.DbgSetAutoCommentAt

def DbgClearAutoCommentRange(start, end):
    return __x64dbg.DbgClearAutoCommentRange(start, end)
DbgClearAutoCommentRange = __x64dbg.DbgClearAutoCommentRange

def DbgSetAutoLabelAt(addr, text):
    return __x64dbg.DbgSetAutoLabelAt(addr, text)
DbgSetAutoLabelAt = __x64dbg.DbgSetAutoLabelAt

def DbgClearAutoLabelRange(start, end):
    return __x64dbg.DbgClearAutoLabelRange(start, end)
DbgClearAutoLabelRange = __x64dbg.DbgClearAutoLabelRange

def DbgSetAutoBookmarkAt(addr):
    return __x64dbg.DbgSetAutoBookmarkAt(addr)
DbgSetAutoBookmarkAt = __x64dbg.DbgSetAutoBookmarkAt

def DbgClearAutoBookmarkRange(start, end):
    return __x64dbg.DbgClearAutoBookmarkRange(start, end)
DbgClearAutoBookmarkRange = __x64dbg.DbgClearAutoBookmarkRange

def DbgSetAutoFunctionAt(start, end):
    return __x64dbg.DbgSetAutoFunctionAt(start, end)
DbgSetAutoFunctionAt = __x64dbg.DbgSetAutoFunctionAt

def DbgClearAutoFunctionRange(start, end):
    return __x64dbg.DbgClearAutoFunctionRange(start, end)
DbgClearAutoFunctionRange = __x64dbg.DbgClearAutoFunctionRange

def DbgGetStringAt(addr, text):
    return __x64dbg.DbgGetStringAt(addr, text)
DbgGetStringAt = __x64dbg.DbgGetStringAt

def GuiDisasmAt(addr, cip):
    return __x64dbg.GuiDisasmAt(addr, cip)
GuiDisasmAt = __x64dbg.GuiDisasmAt

def GuiAddLogMessage(msg):
    return __x64dbg.GuiAddLogMessage(msg)
GuiAddLogMessage = __x64dbg.GuiAddLogMessage

def GuiLogClear():
    return __x64dbg.GuiLogClear()
GuiLogClear = __x64dbg.GuiLogClear

def GuiUpdateAllViews():
    return __x64dbg.GuiUpdateAllViews()
GuiUpdateAllViews = __x64dbg.GuiUpdateAllViews

def GuiUpdateRegisterView():
    return __x64dbg.GuiUpdateRegisterView()
GuiUpdateRegisterView = __x64dbg.GuiUpdateRegisterView

def GuiUpdateDisassemblyView():
    return __x64dbg.GuiUpdateDisassemblyView()
GuiUpdateDisassemblyView = __x64dbg.GuiUpdateDisassemblyView

def GuiUpdateBreakpointsView():
    return __x64dbg.GuiUpdateBreakpointsView()
GuiUpdateBreakpointsView = __x64dbg.GuiUpdateBreakpointsView

def GuiUpdateWindowTitle(filename):
    return __x64dbg.GuiUpdateWindowTitle(filename)
GuiUpdateWindowTitle = __x64dbg.GuiUpdateWindowTitle

def GuiGetWindowHandle():
    return __x64dbg.GuiGetWindowHandle()
GuiGetWindowHandle = __x64dbg.GuiGetWindowHandle

def GuiDumpAt(va):
    return __x64dbg.GuiDumpAt(va)
GuiDumpAt = __x64dbg.GuiDumpAt

def GuiScriptAdd(count, lines):
    return __x64dbg.GuiScriptAdd(count, lines)
GuiScriptAdd = __x64dbg.GuiScriptAdd

def GuiScriptClear():
    return __x64dbg.GuiScriptClear()
GuiScriptClear = __x64dbg.GuiScriptClear

def GuiScriptSetIp(line):
    return __x64dbg.GuiScriptSetIp(line)
GuiScriptSetIp = __x64dbg.GuiScriptSetIp

def GuiScriptError(line, message):
    return __x64dbg.GuiScriptError(line, message)
GuiScriptError = __x64dbg.GuiScriptError

def GuiScriptSetTitle(title):
    return __x64dbg.GuiScriptSetTitle(title)
GuiScriptSetTitle = __x64dbg.GuiScriptSetTitle

def GuiScriptSetInfoLine(line, info):
    return __x64dbg.GuiScriptSetInfoLine(line, info)
GuiScriptSetInfoLine = __x64dbg.GuiScriptSetInfoLine

def GuiScriptMessage(message):
    return __x64dbg.GuiScriptMessage(message)
GuiScriptMessage = __x64dbg.GuiScriptMessage

def GuiScriptMsgyn(message):
    return __x64dbg.GuiScriptMsgyn(message)
GuiScriptMsgyn = __x64dbg.GuiScriptMsgyn

def GuiScriptEnableHighlighting(enable):
    return __x64dbg.GuiScriptEnableHighlighting(enable)
GuiScriptEnableHighlighting = __x64dbg.GuiScriptEnableHighlighting

def GuiSymbolLogAdd(message):
    return __x64dbg.GuiSymbolLogAdd(message)
GuiSymbolLogAdd = __x64dbg.GuiSymbolLogAdd

def GuiSymbolLogClear():
    return __x64dbg.GuiSymbolLogClear()
GuiSymbolLogClear = __x64dbg.GuiSymbolLogClear

def GuiSymbolSetProgress(percent):
    return __x64dbg.GuiSymbolSetProgress(percent)
GuiSymbolSetProgress = __x64dbg.GuiSymbolSetProgress

def GuiSymbolRefreshCurrent():
    return __x64dbg.GuiSymbolRefreshCurrent()
GuiSymbolRefreshCurrent = __x64dbg.GuiSymbolRefreshCurrent

def GuiReferenceAddColumn(width, title):
    return __x64dbg.GuiReferenceAddColumn(width, title)
GuiReferenceAddColumn = __x64dbg.GuiReferenceAddColumn

def GuiReferenceSetRowCount(count):
    return __x64dbg.GuiReferenceSetRowCount(count)
GuiReferenceSetRowCount = __x64dbg.GuiReferenceSetRowCount

def GuiReferenceGetRowCount():
    return __x64dbg.GuiReferenceGetRowCount()
GuiReferenceGetRowCount = __x64dbg.GuiReferenceGetRowCount

def GuiReferenceDeleteAllColumns():
    return __x64dbg.GuiReferenceDeleteAllColumns()
GuiReferenceDeleteAllColumns = __x64dbg.GuiReferenceDeleteAllColumns

def GuiReferenceInitialize(name):
    return __x64dbg.GuiReferenceInitialize(name)
GuiReferenceInitialize = __x64dbg.GuiReferenceInitialize

def GuiReferenceSetCellContent(row, col, str):
    return __x64dbg.GuiReferenceSetCellContent(row, col, str)
GuiReferenceSetCellContent = __x64dbg.GuiReferenceSetCellContent

def GuiReferenceGetCellContent(row, col):
    return __x64dbg.GuiReferenceGetCellContent(row, col)
GuiReferenceGetCellContent = __x64dbg.GuiReferenceGetCellContent

def GuiReferenceReloadData():
    return __x64dbg.GuiReferenceReloadData()
GuiReferenceReloadData = __x64dbg.GuiReferenceReloadData

def GuiReferenceSetSingleSelection(index, scroll):
    return __x64dbg.GuiReferenceSetSingleSelection(index, scroll)
GuiReferenceSetSingleSelection = __x64dbg.GuiReferenceSetSingleSelection

def GuiReferenceSetProgress(progress):
    return __x64dbg.GuiReferenceSetProgress(progress)
GuiReferenceSetProgress = __x64dbg.GuiReferenceSetProgress

def GuiReferenceSetSearchStartCol(col):
    return __x64dbg.GuiReferenceSetSearchStartCol(col)
GuiReferenceSetSearchStartCol = __x64dbg.GuiReferenceSetSearchStartCol

def GuiStackDumpAt(addr, csp):
    return __x64dbg.GuiStackDumpAt(addr, csp)
GuiStackDumpAt = __x64dbg.GuiStackDumpAt

def GuiUpdateDumpView():
    return __x64dbg.GuiUpdateDumpView()
GuiUpdateDumpView = __x64dbg.GuiUpdateDumpView

def GuiUpdateThreadView():
    return __x64dbg.GuiUpdateThreadView()
GuiUpdateThreadView = __x64dbg.GuiUpdateThreadView

def GuiUpdateMemoryView():
    return __x64dbg.GuiUpdateMemoryView()
GuiUpdateMemoryView = __x64dbg.GuiUpdateMemoryView

def GuiAddRecentFile(file):
    return __x64dbg.GuiAddRecentFile(file)
GuiAddRecentFile = __x64dbg.GuiAddRecentFile

def GuiSetLastException(exception):
    return __x64dbg.GuiSetLastException(exception)
GuiSetLastException = __x64dbg.GuiSetLastException

def GuiGetDisassembly(addr, text):
    return __x64dbg.GuiGetDisassembly(addr, text)
GuiGetDisassembly = __x64dbg.GuiGetDisassembly

def GuiMenuAdd(hMenu, title):
    return __x64dbg.GuiMenuAdd(hMenu, title)
GuiMenuAdd = __x64dbg.GuiMenuAdd

def GuiMenuAddEntry(hMenu, title):
    return __x64dbg.GuiMenuAddEntry(hMenu, title)
GuiMenuAddEntry = __x64dbg.GuiMenuAddEntry

def GuiMenuAddSeparator(hMenu):
    return __x64dbg.GuiMenuAddSeparator(hMenu)
GuiMenuAddSeparator = __x64dbg.GuiMenuAddSeparator

def GuiMenuClear(hMenu):
    return __x64dbg.GuiMenuClear(hMenu)
GuiMenuClear = __x64dbg.GuiMenuClear

def GuiGetLineWindow(title, text):
    return __x64dbg.GuiGetLineWindow(title, text)
GuiGetLineWindow = __x64dbg.GuiGetLineWindow

def GuiAutoCompleteAddCmd(cmd):
    return __x64dbg.GuiAutoCompleteAddCmd(cmd)
GuiAutoCompleteAddCmd = __x64dbg.GuiAutoCompleteAddCmd

def GuiAutoCompleteDelCmd(cmd):
    return __x64dbg.GuiAutoCompleteDelCmd(cmd)
GuiAutoCompleteDelCmd = __x64dbg.GuiAutoCompleteDelCmd

def GuiAutoCompleteClearAll():
    return __x64dbg.GuiAutoCompleteClearAll()
GuiAutoCompleteClearAll = __x64dbg.GuiAutoCompleteClearAll

def GuiAddStatusBarMessage(msg):
    return __x64dbg.GuiAddStatusBarMessage(msg)
GuiAddStatusBarMessage = __x64dbg.GuiAddStatusBarMessage

def GuiUpdateSideBar():
    return __x64dbg.GuiUpdateSideBar()
GuiUpdateSideBar = __x64dbg.GuiUpdateSideBar

def GuiRepaintTableView():
    return __x64dbg.GuiRepaintTableView()
GuiRepaintTableView = __x64dbg.GuiRepaintTableView

def GuiUpdatePatches():
    return __x64dbg.GuiUpdatePatches()
GuiUpdatePatches = __x64dbg.GuiUpdatePatches

def GuiUpdateCallStack():
    return __x64dbg.GuiUpdateCallStack()
GuiUpdateCallStack = __x64dbg.GuiUpdateCallStack

def _plugin_logprintf(format):
    return __x64dbg._plugin_logprintf(format)
_plugin_logprintf = __x64dbg._plugin_logprintf
# This file is compatible with both classic and new-style classes.


